; features.ini
; Configure the installation of other programs that SPPAS could use.
; -------------------------------------------------------------------------
;                           S P P A S
;            the automatic annotation and analysis of speech
;
;               Copyright (C) 2011-2026  Brigitte Bigi, CNRS
;        Laboratoire Parole et Langage, Aix-en-Provence, France
;-------------------------------------------------------------------------
;
; Use [Section] to add a new feature of SPPAS requiring dependencies.
;
; The features corresponds to 3 types of installation:
;      - deps: package/programs dependencies
;      - lang: linguistic resources
;      - annot: annotation resources
; ---------------------------------------------------------------------------
;
; For type = deps:
;
; * Attributes starting with "req_" concern system package dependencies.
;   Only unix-based systems can have package requirements. If they don't,
;   the corresponding req_ attribute is missing or empty or is "nil".
;     - req_deb: apt package manager
;     - req_ios: brew package manager
;   Other package managers are not implemented yet.
;
; * Attribute 'pip' concerns installation of Pypis packages:
;     - use whitespace to separate packages
;     - use ':' to separate the package name (at left) and the
;       version constraints (at right)
;
; * Attribute 'pip_alt' is for the installation of alternative Pypis
;   packages, in case the regular ones failed to be installed.
;
; * Attribute 'pip_opt' is for passing options to pip install system:
;     - use ':' to separate the package name (at left) and its options
;       (at right), or give the options only to apply them to all the
;       packages of the feature
;     - use one line for each package
;
; * Attribute "cmd_" is a command to be executed for a given system.
;
; deb/ios/rpm/win
;

; ---------------------------------------------------------------------------
; deps
; ---------------------------------------------------------------------------

[sppas]
type = deps
brief = SPPAS Source Code
desc = Updates the internal 'sppas' Python package
enable = false
pip = sppas
pip_test = sppas

[wintools]
type = deps
brief = Windows Executables
desc = Installs Julius, FFmpeg and Praat executables inside the SPPAS package
enable = true
cmd_win = "$PY" "$SPPAS\sppas\bin\wintools.py"
cmd_test = julius --version

[mactools]
type = deps
brief = macOS Executables
desc = Installs Homebrew, then Julius, FFmpeg and Praat system-wide via Homebrew
enable = true
cmd_ios = "$PY" "$SPPAS/sppas/bin/mactools.py"
cmd_test = julius --version

[wxpython]
type = deps
brief = Graphical User Interface
desc = Enables graphical interaction with SPPAS using its Graphical User Interface
enable = true
req_deb = make:>;0.0 gcc:>;0.0 python3-wx*
pip = wxpython:>=4.1
pip_opt = -f https://wxpython.org/Phoenix/snapshot-builds/
pip_test = wx

[formants]
type = deps
brief = F1/F2 Formants detection
desc = Enables the estimation of F1 and F2 formants, self-estimated or estimated by Praat via parselmouth tool
enable = false
pip = numpy:>2.0,<2.3.0 scipy:>=1.13.0,<=1.17 praat-parselmouth:<=0.4.7
pip_test = numpy scipy parselmouth

[stt]
type = deps
brief = SpeechToText
desc = Enables OpenAI Whisper for automatic speech to text transcription into the Inter Pausal Units
enable = false
pip = torch openai-whisper
pip_opt = torch:--index-url https://download.pytorch.org/whl/cpu
; Uncomment/Comment the pip_opt line for CPU/GPU support respectively.
pip_test = whisper
cmd_test = ffmpeg -h

[audioplay]
type = deps
brief = Audio playback support
desc = Adds audio playback support in the SPPAS Edit page
enable = true
pip = miniaudio:>=1.0
pip_alt = sounddevice:>=0.4 PyAudio:>0.1
pip_test = miniaudio|sounddevice|pyaudio
req_deb = make:>;0.0 gcc:>;0.0 libasound2-dev:>;0.0 libportaudio2:>;0.0 portaudio19-dev:>;0.0
req_ios = portaudio:>;1

[video]
type = deps
brief = Image and video support
desc = Enables image and video processing
enable = false
pip = numpy:>2.0,<2.3.0 opencv-contrib-python-headless:>=4.5.4,<5.0 opencv-contrib-python:>=4.5.4,<5.0
pip_test = numpy cv2

[mediapipe]
type = deps
brief = Mediapipe detections
desc = Integrates Mediapipe-numpy2 for advanced video processing: used by the Face detection, Face landmarks and Hands detection annotations.
enable = false
pip = numpy:>2.0,<2.3.0 mediapipe-numpy2
pip_test = numpy cv2 mediapipe

; ---------------------------------------------------------------------------
; annot. The name of the section is the 'id' of the annotation.
; ---------------------------------------------------------------------------

[facedetect]
type = annot
brief = Face detection
desc = Models for automatic face detection in images
enable = false


[facemark]
type = annot
brief = Face landmarks
desc = Models for automatic detection of 68 facial landmarks in images
enable = false

[handpose]
type = annot
brief = Hands and pose detection
desc = Models for automatic detection of 21 sights on hands in images
enable = false

; ---------------------------------------------------------------------------
; spin. The name of the section is the 'id' of the spin-off.
; ---------------------------------------------------------------------------

[autocs]
type = spin
brief = Auto-CS
desc = Automatic generation of Cued Speech
enable = false
url = https://sourceforge.net/projects/autocs/files/
version = 2.1

; ---------------------------------------------------------------------------
; lang. The name of the section is the iso of the language.
; ---------------------------------------------------------------------------

[eng]
type = lang
brief = English
desc = Support of American English Language
enable = false

[fra]
type = lang
brief = French
desc = Support of French Language
enable = false

[frq]
type = lang
brief = Quebec French
desc = Support of Quebec French Language
enable = false

[ben]
type = lang
brief = Bengali
desc = Support of Bengali Language
enable = false

[cat]
type = lang
brief = Catalan
desc = Support of Catalan Language
enable = false

[cmn]
type = lang
brief = Mandarin Chinese
desc = Support of Mandarin Chinese Language
enable = false

[deu]
type = lang
brief = German
desc = Support of German Language
enable = false

[dut]
type = lang
brief = Dutch
desc = Support of Dutch Language
enable = false

[hun]
type = lang
brief = Hungarian
desc = Support of Hungarian Language
enable = false

[ita]
type = lang
brief = Italian
desc = Support of Italian Language
enable = false

[jpn]
type = lang
brief = Japanese
desc = Support of Japanese Language
enable = false

[kor]
type = lang
brief = Korean
desc = Support of Korean Language
enable = false

[nan]
type = lang
brief = Min Nan
desc = Support of Min Nan Language
enable = false

[pcm]
type = lang
brief = Naija
desc = Support of Naija Language
enable = false

[pes]
type = lang
brief = Persian
desc = Support of Persian Language
enable = false

[pol]
type = lang
brief = Polish language
desc = Support of Polish Language
enable = false

[por]
type = lang
brief = Portuguese
desc = Support of Portuguese Language
enable = false

[spa]
type = lang
brief = Spanish
desc = Support of Spanish Language
enable = false

[vie]
type = lang
brief = Vietnamese
desc = Support of Vietnamese Language
enable = false

[yue]
type = lang
brief = Cantonese
desc = Support of Cantonese Language
enable = false
